### ISSUE TITLE
Home and Profile page: Make tabs navigable using react router v6

### ISSUE THREAD

**Issue by zachan-dev** [zachan-dev/reactjs-django-twitter-clone#2]
**Current Result**: Currently when navigating to tabs, such as media in the profile, I need to go to /profile/:username and click media tab.

**Expected Result**: When I click the tab, I expect react routes to /profile/:username/:tabname
  And when I navigate to /profile/:username/:tabname, I expect profile page with the specified tab selected.

**Comment by danmolloy** [comment]
Hi zachan-dev, 
Can I please help you with this issue?
Best, Dan

**Comment by zachan-dev** [comment]
Hi @danmolloy Dan,

Sure, thanks.

Note that I didn't refactor or have good structure on the tab panel components on both Home and Profile pages. You may want to refactor the code to reduce repetition.

Thanks,
Zach

**Comment by danmolloy** [comment]
Sure, that's fine. Could you please assign me the issue?

Thanks, Dan

**Comment by danmolloy** [comment]
Hi Zach, 

I'm sorry for the delay with this issue. I’ve not yet managed to start - I’m having ongoing trouble with installations. I was hoping to resolve them myself but these are proving to be stubborn challenges!

I’m much less familiar with Django than I am React, which I honestly think is the primary issue. I wonder however if you could just double check your Getting Started section of Readme? I’ve been trying to follow it without any luck.

Just to run you through the trouble I'm having:

Prequisites
[x] npm
[x] python
[x] python3

Installation
[x] 1. Clone the repo
[x] 2. Activate python virtual environment 
     (```python3 -m venv testVenv 
       source testVenv/bin/activate``` - slightly different commands on a mac is per [python.org](https://docs.python.org/3/tutorial/venv.html)) 
[] 3. Install PIP packages (`pip install -r requirements.txt` - I assume it’s .txt rather than .py?). First issue is here.
<img width="617" alt="pip install -r requirements" src="https://user-images.githubusercontent.com/64697812/129462598-90013dfd-1c1b-4283-aa9f-a502eba3a932.png">

I'm not to sure what to do there sorry (again, I'm much more familiar with JS/React). Moving on..

[x] 4. Install NPM packages
[x] 5. Build React outputs
[] 6. Django Init. I think the issues here are due to step 3. A couple of packages aren't found (ie django and environ.
<img width="744" alt="manage py makemigrations" src="https://user-images.githubusercontent.com/64697812/129462643-efcc77c4-981b-423e-a28a-f26a5ba9d104.png">

After running `pip install Django` and `pip install environ`, the issue is the following: 
<img width="944" alt="Screenshot 2021-08-15 at 09 13 47" src="https://user-images.githubusercontent.com/64697812/129462665-54d7616c-a897-423b-8c52-77e1882e6aec.png">

Needless to say, `python manage.py runserver` fails.

Sorry I haven't been able to resolve this myself! I hope you can help me so I can contribute to your project.

Many thanks,
Dan

**Comment by zachan-dev** [comment]
Hi @danmolloy,

Thanks for reporting your installation problem. I'm glad that you asked and I got this feedback.
I'll try to reproduce your problem. But I found a discussion in StackOverflow that maybe helpful to resolve this mac-specific problem: https://stackoverflow.com/questions/20170895/mac-virtualenv-pip-postgresql-error-pg-config-executable-not-found

Thanks,
Zach

**Comment by danmolloy** [comment]
Hi Zach,
Thanks for that. Following that link I downloaded postgresql and ran the installation as per the docs.

I'm still having a bit of trouble running `python manage.py makemigrations network`. 

Just to bring you up to speed with what I'm running now to get there...

```
git clone https://github.com/zachan-dev/reactjs-django-twitter-clone.git
python3 -m venv testVenv 
source testVenv/bin/activate
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
cd reactjs-django-twitter-clone
pip install -r requirements.txt
cd frontend
npm install
npm run dev 
cd .. 
python manage.py makemigrations network
```

There was then an error regarding SECRET_KEY and DATABASE_URL. 
I made a `.env` file, although just set the database to www.example.com. My experience with databases are limited to just MongoDB so I'm a bit out of my depth here and not really sure what to set it to. Needless to say it throws a new error:
<img width="1141" alt="Screenshot 2021-08-16 at 14 30 10" src="https://user-images.githubusercontent.com/64697812/129512351-ea936b6f-5033-4865-9aff-4d06abf20ef8.png">

Just wondering if you have a simple solution what to set the dbURL to?
Otherwise I'm wondering if I can just run the frontend and dummy the backend.. 
This isn't quite as straightforward as I had expected sorry. I wouldn't be offended if you'd rather unassign me and find someone a bit more experienced with both React Router and Django. I'm sure there are plenty of people here that are!

Best, Dan

**Comment by zachan-dev** [comment]
Hi @danmolloy,

I can see you are very near to make it working. Please stay with me, it's okay if things go slow as I'm not in a hurry.

I'm sorry I didn't provide enough installation instructions. Yes you should create `.env`, the contents should be as follows:

> #BASIC CONFIG
> SECRET_KEY=13kl@xtukpwe&xj2xoysxe9_6=tf@f8ewxer5n&ifnd46+6$%8
> DEBUG=True
> DATABASE_URL=

Simply leave DATABASE_URL as empty. Please try this and tell me if u are experiencing further issues, I will work for you.

Btw we can have a chat if you don't mind. I can work you through the installation process.
You can PM My LinkedIn: https://www.linkedin.com/in/zach-chan-hk/

Thanks,
Zach

**Comment by danmolloy** [comment]
Server is running!! Thanks for your messages Zach. I'll get started on the issue tomorrow morning.
Best, Dan

**Comment by zachan-dev** [comment]
No problem! Thanks Dan!

**Comment by zachan-dev** [comment]
@danmolloy Thanks for your contribution! The fix works perfectly! About the styling, I have fixed that with a new commit.

One more thing, would you mind doing the same thing for Home Page tabs as well? I tried to do but the sidebar Home button is not active when I clicked the `Following` tab. I wish to click `All` to '/' and `Following` to '/following'...

Thanks in advance!

**Comment by danmolloy** [comment]
Fantastic! Yes of course. I should have that done tomorrow or the next day.

Best wishes,
Dan
